# docker-compose.yml
version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf/custom.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 4400:80
  php:
    build: ./php
    volumes:
      - ./listener/bch_listener:/www/bch_listener
    command: php /www/bch_listener/listener.php
  app:
    image: phpswoole/swoole
    environment:
      SWOOLE_EXT_ASYNC: enabled
      SWOOLE_EXT_ORM: disabled
      SWOOLE_EXT_POSTGRESQL: disabled
      SWOOLE_EXT_SERIALIZE: enabled
    volumes:
      - ./server:/var/www      
    ports:
      - 5000:9501  
  redis:
    image: redis
    command: ["sh", "-c", "exec redis-server"]
  client:
    image: nginx
    volumes:
      - ./client/dist:/usr/share/nginx/html
    ports:
      - 8099:80
